,pullid,pulls_number,pulltitle,pullsbody,pullsuserlogin,pullsuserid,pullauthordate,author_association,merged_status,stats_addns,stats_delns,stats_changed_files,pull_repo_desc,pull_repo_lang,pull_commit_sha,pull_commit_message
0,https://api.github.com/repos/mozilla/git-repo/pulls/5,5,Bug 1653169 - Use py2 for this old copy of repo,"This is a stop-gap for [bug 1653169](https://bugzilla.mozilla.org/show_bug.cgi?id=1653169), working around the bustage of this old copy of the repo tool with python3. The followup will be to merge from upstream.",nthomas-mozilla,942272,2020-07-16T23:57:38Z,CONTRIBUTOR,True,1,1,1,git-repo with modifcation to fix private repo access,Python,3ffaa6053e0fa17b0732eff9ea8f18616645ebee,Use py2 for this old copy of repo
1,https://api.github.com/repos/mozilla/git-repo/pulls/1,1,catch all 400 http errors identically,"example of why this is needed: https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-macosx64/release-mozilla-release-firefox-linux64_partner_repacks-bm84-build1-build23.txt.gz

verified this patch fixes things locally.

thanks to @rail for discovering and investigating.",lundjordan,1648433,2016-12-08T22:49:48Z,CONTRIBUTOR,True,2,1,1,git-repo with modifcation to fix private repo access,Python,d230ac1b27857cc7b254a8f23dc570217ebd07a4,catch all 400 http errors identically
